# Sprint 12

# Nivell 1

## 1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

- Llista de publicacions (/posts)
- Llista d’usuaris (/users)
- Llista de tasques (/todos)

In [94]:
import pandas as pd
import requests
import json

In [18]:
response_posts = requests.get("https://jsonplaceholder.typicode.com/posts")
posts = response_posts.json()
print(posts)

[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'}, {'userId': 1, 'id': 5, 'title': 'nesciunt quas odio', 'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'}, {'userId': 1, 'id': 6, 'title': 'dolorem eum magni eos aperiam quia', 'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'}, {'userId': 1, 'id': 7, 'title': 'magnam facilis autem', 'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'}, {'userId': 1, 'id': 8, 'title': 'dolorem dolore est ipsam', 'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'}, {'userId': 1, 'id': 9, 'title': 'nesciunt iure omnis dolorem tempora et accusantium', 'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'}, {'userId': 1, 'id': 10, 'title': 'optio molestias id quia eum', 'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'}, {'userId': 2, 'id': 11, 'title': 'et ea vero quia laudantium autem', 'body': 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi'}, {'userId': 2, 'id': 12, 'title': 'in quibusdam tempore odit est dolorem', 'body': 'itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio'}, {'userId': 2, 'id': 13, 'title': 'dolorum ut in voluptas mollitia et saepe quo animi', 'body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam'}, {'userId': 2, 'id': 14, 'title': 'voluptatem eligendi optio', 'body': 'fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum'}, {'userId': 2, 'id': 15, 'title': 'eveniet quod temporibus', 'body': 'reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae'}, {'userId': 2, 'id': 16, 'title': 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio', 'body': 'suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta'}, {'userId': 2, 'id': 17, 'title': 'fugit voluptas sed molestias voluptatem provident', 'body': 'eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo'}, {'userId': 2, 'id': 18, 'title': 'voluptate et itaque vero tempora molestiae', 'body': 'eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam'}, {'userId': 2, 'id': 19, 'title': 'adipisci placeat illum aut reiciendis qui', 'body': 'illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas'}, {'userId': 2, 'id': 20, 'title': 'doloribus ad provident suscipit at', 'body': 'qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo'}, {'userId': 3, 'id': 21, 'title': 'asperiores ea ipsam voluptatibus modi minima quia sint', 'body': 'repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt'}, {'userId': 3, 'id': 22, 'title': 'dolor sint quo a velit explicabo quia nam', 'body': 'eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse'}, {'userId': 3, 'id': 23, 'title': 'maxime id vitae nihil numquam', 'body': 'veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis'}, {'userId': 3, 'id': 24, 'title': 'autem hic labore sunt dolores incidunt', 'body': 'enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt'}, {'userId': 3, 'id': 25, 'title': 'rem alias distinctio quo quis', 'body': 'ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio'}, {'userId': 3, 'id': 26, 'title': 'est et quae odit qui non', 'body': 'similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero'}, {'userId': 3, 'id': 27, 'title': 'quasi id et eos tenetur aut quo autem', 'body': 'eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur'}, {'userId': 3, 'id': 28, 'title': 'delectus ullam et corporis nulla voluptas sequi', 'body': 'non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum'}, {'userId': 3, 'id': 29, 'title': 'iusto eius quod necessitatibus culpa ea', 'body': 'odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores'}, {'userId': 3, 'id': 30, 'title': 'a quo magni similique perferendis', 'body': 'alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia'}, {'userId': 4, 'id': 31, 'title': 'ullam ut quidem id aut vel consequuntur', 'body': 'debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae'}, {'userId': 4, 'id': 32, 'title': 'doloremque illum aliquid sunt', 'body': 'deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime'}, {'userId': 4, 'id': 33, 'title': 'qui explicabo molestiae dolorem', 'body': 'rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod'}, {'userId': 4, 'id': 34, 'title': 'magnam ut rerum iure', 'body': 'ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis'}, {'userId': 4, 'id': 35, 'title': 'id nihil consequatur molestias animi provident', 'body': 'nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit'}, {'userId': 4, 'id': 36, 'title': 'fuga nam accusamus voluptas reiciendis itaque', 'body': 'ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore'}, {'userId': 4, 'id': 37, 'title': 'provident vel ut sit ratione est', 'body': 'debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui'}, {'userId': 4, 'id': 38, 'title': 'explicabo et eos deleniti nostrum ab id repellendus', 'body': 'animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure'}, {'userId': 4, 'id': 39, 'title': 'eos dolorem iste accusantium est eaque quam', 'body': 'corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex'}, {'userId': 4, 'id': 40, 'title': 'enim quo cumque', 'body': 'ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam'}, {'userId': 5, 'id': 41, 'title': 'non est facere', 'body': 'molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe'}, {'userId': 5, 'id': 42, 'title': 'commodi ullam sint et excepturi error explicabo praesentium voluptas', 'body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut'}, {'userId': 5, 'id': 43, 'title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis', 'body': 'similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis'}, {'userId': 5, 'id': 44, 'title': 'optio dolor molestias sit', 'body': 'temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae'}, {'userId': 5, 'id': 45, 'title': 'ut numquam possimus omnis eius suscipit laudantium iure', 'body': 'est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem'}, {'userId': 5, 'id': 46, 'title': 'aut quo modi neque nostrum ducimus', 'body': 'voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid'}, {'userId': 5, 'id': 47, 'title': 'quibusdam cumque rem aut deserunt', 'body': 'voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate'}, {'userId': 5, 'id': 48, 'title': 'ut voluptatem illum ea doloribus itaque eos', 'body': 'voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit'}, {'userId': 5, 'id': 49, 'title': 'laborum non sunt aut ut assumenda perspiciatis voluptas', 'body': 'inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut'}, {'userId': 5, 'id': 50, 'title': 'repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem', 'body': 'error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur'}, {'userId': 6, 'id': 51, 'title': 'soluta aliquam aperiam consequatur illo quis voluptas', 'body': 'sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem'}, {'userId': 6, 'id': 52, 'title': 'qui enim et consequuntur quia animi quis voluptate quibusdam', 'body': 'iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum'}, {'userId': 6, 'id': 53, 'title': 'ut quo aut ducimus alias', 'body': 'minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique'}, {'userId': 6, 'id': 54, 'title': 'sit asperiores ipsam eveniet odio non quia', 'body': 'totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia'}, {'userId': 6, 'id': 55, 'title': 'sit vel voluptatem et non libero', 'body': 'debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit'}, {'userId': 6, 'id': 56, 'title': 'qui et at rerum necessitatibus', 'body': 'aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi'}, {'userId': 6, 'id': 57, 'title': 'sed ab est est', 'body': 'at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est'}, {'userId': 6, 'id': 58, 'title': 'voluptatum itaque dolores nisi et quasi', 'body': 'veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam'}, {'userId': 6, 'id': 59, 'title': 'qui commodi dolor at maiores et quis id accusantium', 'body': 'perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt'}, {'userId': 6, 'id': 60, 'title': 'consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere', 'body': 'asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis'}, {'userId': 7, 'id': 61, 'title': 'voluptatem doloribus consectetur est ut ducimus', 'body': 'ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit'}, {'userId': 7, 'id': 62, 'title': 'beatae enim quia vel', 'body': 'enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio'}, {'userId': 7, 'id': 63, 'title': 'voluptas blanditiis repellendus animi ducimus error sapiente et suscipit', 'body': 'enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta'}, {'userId': 7, 'id': 64, 'title': 'et fugit quas eum in in aperiam quod', 'body': 'id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui'}, {'userId': 7, 'id': 65, 'title': 'consequatur id enim sunt et et', 'body': 'voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur'}, {'userId': 7, 'id': 66, 'title': 'repudiandae ea animi iusto', 'body': 'officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe'}, {'userId': 7, 'id': 67, 'title': 'aliquid eos sed fuga est maxime repellendus', 'body': 'reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae'}, {'userId': 7, 'id': 68, 'title': 'odio quis facere architecto reiciendis optio', 'body': 'magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit'}, {'userId': 7, 'id': 69, 'title': 'fugiat quod pariatur odit minima', 'body': 'officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a'}, {'userId': 7, 'id': 70, 'title': 'voluptatem laborum magni', 'body': 'sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore'}, {'userId': 8, 'id': 71, 'title': 'et iusto veniam et illum aut fuga', 'body': 'occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis'}, {'userId': 8, 'id': 72, 'title': 'sint hic doloribus consequatur eos non id', 'body': 'quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit'}, {'userId': 8, 'id': 73, 'title': 'consequuntur deleniti eos quia temporibus ab aliquid at', 'body': 'voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut'}, {'userId': 8, 'id': 74, 'title': 'enim unde ratione doloribus quas enim ut sit sapiente', 'body': 'odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora'}, {'userId': 8, 'id': 75, 'title': 'dignissimos eum dolor ut enim et delectus in', 'body': 'commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem'}, {'userId': 8, 'id': 76, 'title': 'doloremque officiis ad et non perferendis', 'body': 'ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio'}, {'userId': 8, 'id': 77, 'title': 'necessitatibus quasi exercitationem odio', 'body': 'modi ut in nulla repudiandae dolorum nostrum eos\naut consequatur omnis\nut incidunt est omnis iste et quam\nvoluptates sapiente aliquam asperiores nobis amet corrupti repudiandae provident'}, {'userId': 8, 'id': 78, 'title': 'quam voluptatibus rerum veritatis', 'body': 'nobis facilis odit tempore cupiditate quia\nassumenda doloribus rerum qui ea\nillum et qui totam\naut veniam repellendus'}, {'userId': 8, 'id': 79, 'title': 'pariatur consequatur quia magnam autem omnis non amet', 'body': 'libero accusantium et et facere incidunt sit dolorem\nnon excep

In [20]:
response_users = requests.get("https://jsonplaceholder.typicode.com/users")
users = response_users.json()
print(users)

[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': {'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}, 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': {'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}, 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': {'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}, 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': {'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}, 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': {'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}, 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': {'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}, 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': {'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}, 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': {'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}, 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]

In [22]:
response_todos = requests.get("https://jsonplaceholder.typicode.com/todos")
todos = response_todos.json()
print(todos)

[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}, {'userId': 1, 'id': 2, 'title': 'quis ut nam facilis et officia qui', 'completed': False}, {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False}, {'userId': 1, 'id': 4, 'title': 'et porro tempora', 'completed': True}, {'userId': 1, 'id': 5, 'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum', 'completed': False}, {'userId': 1, 'id': 6, 'title': 'qui ullam ratione quibusdam voluptatem quia omnis', 'completed': False}, {'userId': 1, 'id': 7, 'title': 'illo expedita consequatur quia in', 'completed': False}, {'userId': 1, 'id': 8, 'title': 'quo adipisci enim quam ut ab', 'completed': True}, {'userId': 1, 'id': 9, 'title': 'molestiae perspiciatis ipsa', 'completed': False}, {'userId': 1, 'id': 10, 'title': 'illo est ratione doloremque quia maiores aut', 'completed': True}, {'userId': 1, 'id': 11, 'title': 'vero rerum temporibus dolor', 'completed': True}, {'userId': 1, 'id': 12, 'title': 'ipsa repellendus fugit nisi', 'completed': True}, {'userId': 1, 'id': 13, 'title': 'et doloremque nulla', 'completed': False}, {'userId': 1, 'id': 14, 'title': 'repellendus sunt dolores architecto voluptatum', 'completed': True}, {'userId': 1, 'id': 15, 'title': 'ab voluptatum amet voluptas', 'completed': True}, {'userId': 1, 'id': 16, 'title': 'accusamus eos facilis sint et aut voluptatem', 'completed': True}, {'userId': 1, 'id': 17, 'title': 'quo laboriosam deleniti aut qui', 'completed': True}, {'userId': 1, 'id': 18, 'title': 'dolorum est consequatur ea mollitia in culpa', 'completed': False}, {'userId': 1, 'id': 19, 'title': 'molestiae ipsa aut voluptatibus pariatur dolor nihil', 'completed': True}, {'userId': 1, 'id': 20, 'title': 'ullam nobis libero sapiente ad optio sint', 'completed': True}, {'userId': 2, 'id': 21, 'title': 'suscipit repellat esse quibusdam voluptatem incidunt', 'completed': False}, {'userId': 2, 'id': 22, 'title': 'distinctio vitae autem nihil ut molestias quo', 'completed': True}, {'userId': 2, 'id': 23, 'title': 'et itaque necessitatibus maxime molestiae qui quas velit', 'completed': False}, {'userId': 2, 'id': 24, 'title': 'adipisci non ad dicta qui amet quaerat doloribus ea', 'completed': False}, {'userId': 2, 'id': 25, 'title': 'voluptas quo tenetur perspiciatis explicabo natus', 'completed': True}, {'userId': 2, 'id': 26, 'title': 'aliquam aut quasi', 'completed': True}, {'userId': 2, 'id': 27, 'title': 'veritatis pariatur delectus', 'completed': True}, {'userId': 2, 'id': 28, 'title': 'nesciunt totam sit blanditiis sit', 'completed': False}, {'userId': 2, 'id': 29, 'title': 'laborum aut in quam', 'completed': False}, {'userId': 2, 'id': 30, 'title': 'nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis', 'completed': True}, {'userId': 2, 'id': 31, 'title': 'repudiandae totam in est sint facere fuga', 'completed': False}, {'userId': 2, 'id': 32, 'title': 'earum doloribus ea doloremque quis', 'completed': False}, {'userId': 2, 'id': 33, 'title': 'sint sit aut vero', 'completed': False}, {'userId': 2, 'id': 34, 'title': 'porro aut necessitatibus eaque distinctio', 'completed': False}, {'userId': 2, 'id': 35, 'title': 'repellendus veritatis molestias dicta incidunt', 'completed': True}, {'userId': 2, 'id': 36, 'title': 'excepturi deleniti adipisci voluptatem et neque optio illum ad', 'completed': True}, {'userId': 2, 'id': 37, 'title': 'sunt cum tempora', 'completed': False}, {'userId': 2, 'id': 38, 'title': 'totam quia non', 'completed': False}, {'userId': 2, 'id': 39, 'title': 'doloremque quibusdam asperiores libero corrupti illum qui omnis', 'completed': False}, {'userId': 2, 'id': 40, 'title': 'totam atque quo nesciunt', 'completed': True}, {'userId': 3, 'id': 41, 'title': 'aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit', 'completed': False}, {'userId': 3, 'id': 42, 'title': 'rerum perferendis error quia ut eveniet', 'completed': False}, {'userId': 3, 'id': 43, 'title': 'tempore ut sint quis recusandae', 'completed': True}, {'userId': 3, 'id': 44, 'title': 'cum debitis quis accusamus doloremque ipsa natus sapiente omnis', 'completed': True}, {'userId': 3, 'id': 45, 'title': 'velit soluta adipisci molestias reiciendis harum', 'completed': False}, {'userId': 3, 'id': 46, 'title': 'vel voluptatem repellat nihil placeat corporis', 'completed': False}, {'userId': 3, 'id': 47, 'title': 'nam qui rerum fugiat accusamus', 'completed': False}, {'userId': 3, 'id': 48, 'title': 'sit reprehenderit omnis quia', 'completed': False}, {'userId': 3, 'id': 49, 'title': 'ut necessitatibus aut maiores debitis officia blanditiis velit et', 'completed': False}, {'userId': 3, 'id': 50, 'title': 'cupiditate necessitatibus ullam aut quis dolor voluptate', 'completed': True}, {'userId': 3, 'id': 51, 'title': 'distinctio exercitationem ab doloribus', 'completed': False}, {'userId': 3, 'id': 52, 'title': 'nesciunt dolorum quis recusandae ad pariatur ratione', 'completed': False}, {'userId': 3, 'id': 53, 'title': 'qui labore est occaecati recusandae aliquid quam', 'completed': False}, {'userId': 3, 'id': 54, 'title': 'quis et est ut voluptate quam dolor', 'completed': True}, {'userId': 3, 'id': 55, 'title': 'voluptatum omnis minima qui occaecati provident nulla voluptatem ratione', 'completed': True}, {'userId': 3, 'id': 56, 'title': 'deleniti ea temporibus enim', 'completed': True}, {'userId': 3, 'id': 57, 'title': 'pariatur et magnam ea doloribus similique voluptatem rerum quia', 'completed': False}, {'userId': 3, 'id': 58, 'title': 'est dicta totam qui explicabo doloribus qui dignissimos', 'completed': False}, {'userId': 3, 'id': 59, 'title': 'perspiciatis velit id laborum placeat iusto et aliquam odio', 'completed': False}, {'userId': 3, 'id': 60, 'title': 'et sequi qui architecto ut adipisci', 'completed': True}, {'userId': 4, 'id': 61, 'title': 'odit optio omnis qui sunt', 'completed': True}, {'userId': 4, 'id': 62, 'title': 'et placeat et tempore aspernatur sint numquam', 'completed': False}, {'userId': 4, 'id': 63, 'title': 'doloremque aut dolores quidem fuga qui nulla', 'completed': True}, {'userId': 4, 'id': 64, 'title': 'voluptas consequatur qui ut quia magnam nemo esse', 'completed': False}, {'userId': 4, 'id': 65, 'title': 'fugiat pariatur ratione ut asperiores necessitatibus magni', 'completed': False}, {'userId': 4, 'id': 66, 'title': 'rerum eum molestias autem voluptatum sit optio', 'completed': False}, {'userId': 4, 'id': 67, 'title': 'quia voluptatibus voluptatem quos similique maiores repellat', 'completed': False}, {'userId': 4, 'id': 68, 'title': 'aut id perspiciatis voluptatem iusto', 'completed': False}, {'userId': 4, 'id': 69, 'title': 'doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit', 'completed': False}, {'userId': 4, 'id': 70, 'title': 'ut sequi accusantium et mollitia delectus sunt', 'completed': False}, {'userId': 4, 'id': 71, 'title': 'aut velit saepe ullam', 'completed': False}, {'userId': 4, 'id': 72, 'title': 'praesentium facilis facere quis harum voluptatibus voluptatem eum', 'completed': False}, {'userId': 4, 'id': 73, 'title': 'sint amet quia totam corporis qui exercitationem commodi', 'completed': True}, {'userId': 4, 'id': 74, 'title': 'expedita tempore nobis eveniet laborum maiores', 'completed': False}, {'userId': 4, 'id': 75, 'title': 'occaecati adipisci est possimus totam', 'completed': False}, {'userId': 4, 'id': 76, 'title': 'sequi dolorem sed', 'completed': True}, {'userId': 4, 'id': 77, 'title': 'maiores aut nesciunt delectus exercitationem vel assumenda eligendi at', 'completed': False}, {'userId': 4, 'id': 78, 'title': 'reiciendis est magnam amet nemo iste recusandae impedit quaerat', 'completed': False}, {'userId': 4, 'id': 79, 'title': 'eum ipsa maxime ut', 'completed': True}, {'userId': 4, 'id': 80, 'title': 'tempore molestias dolores rerum sequi voluptates ipsum consequatur', 'completed': True}, {'userId': 5, 'id': 81, 'title': 'suscipit qui totam', 'completed': True}, {'userId': 5, 'id': 82, 'title': 'voluptates eum voluptas et dicta', 'completed': False}, {'userId': 5, 'id': 83, 'title': 'quidem at rerum quis ex aut sit quam', 'completed': True}, {'userId': 5, 'id': 84, 'title': 'sunt veritatis ut voluptate', 'completed': False}, {'userId': 5, 'id': 85, 'title': 'et quia ad iste a', 'completed': True}, {'userId': 5, 'id': 86, 'title': 'incidunt ut saepe autem', 'completed': True}, {'userId': 5, 'id': 87, 'title': 'laudantium quae eligendi consequatur quia et vero autem', 'completed': True}, {'userId': 5, 'id': 88, 'title': 'vitae aut excepturi laboriosam sint aliquam et et accusantium', 'completed': False}, {'userId': 5, 'id': 89, 'title': 'sequi ut omnis et', 'completed': True}, {'userId': 5, 'id': 90, 'title': 'molestiae nisi accusantium tenetur dolorem et', 'completed': True}, {'userId': 5, 'id': 91, 'title': 'nulla quis consequatur saepe qui id expedita', 'completed': True}, {'userId': 5, 'id': 92, 'title': 'in omnis laboriosam', 'completed': True}, {'userId': 5, 'id': 93, 'title': 'odio iure consequatur molestiae quibusdam necessitatibus quia sint', 'completed': True}, {'userId': 5, 'id': 94, 'title': 'facilis modi saepe mollitia', 'completed': False}, {'userId': 5, 'id': 95, 'title': 'vel nihil et molestiae iusto assumenda nemo quo ut', 'completed': True}, {'userId': 5, 'id': 96, 'title': 'nobis suscipit ducimus enim asperiores voluptas', 'completed': False}, {'userId': 5, 'id': 97, 'title': 'dolorum laboriosam eos qui iure aliquam', 'completed': False}, {'userId': 5, 'id': 98, 'title': 'debitis accusantium ut quo facilis nihil quis sapiente necessitatibus', 'completed': True}, {'userId': 5, 'id': 99, 'title': 'neque voluptates ratione', 'completed': False}, {'userId': 5, 'id': 100, 'title': 'excepturi a et neque qui expedita vel voluptate', 'completed': False}, {'userId': 6, 'id': 101, 'title': 'explicabo enim cumque porro aperiam occaecati minima', 'completed': False}, {'userId': 6, 'id': 102, 'title': 'sed ab consequatur', 'completed': False}, {'userId': 6, 'id': 103, 'title': 'non sunt delectus illo nulla tenetur enim omnis', 'completed': False}, {'userId': 6, 'id': 104, 'title': 'excepturi non laudantium quo', 'completed': False}, {'userId': 6, 'id': 105, 'title': 'totam quia dolorem et illum repellat voluptas optio', 'completed': True}, {'userId': 6, 'id': 106, 'title': 'ad illo quis voluptatem temporibus', 'completed': True}, {'userId': 6, 'id': 107, 'title': 'praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt', 'completed': False}, {'userId': 6, 'id': 108, 'title': 'a eos eaque nihil et exercitationem incidunt delectus', 'completed': True}, {'userId': 6, 'id': 109, 'title': 'autem temporibus harum quisquam in culpa', 'completed': True}, {'userId': 6, 'id': 110, 'title': 'aut aut ea corporis', 'completed': True}, {'userId': 6, 'id': 111, 'title': 'magni accusantium labore et id quis provident', 'completed': False}, {'userId': 6, 'id': 112, 'title': 'consectetur impedit quisquam qui deserunt non rerum consequuntur eius', 'completed': False}, {'userId': 6, 'id': 113, 'title': 'quia atque aliquam sunt impedit voluptatum rerum assumenda nisi', 'completed': False}, {'userId': 6, 'id': 114, 'title': 'cupiditate quos possimus corporis quisquam exercitationem beatae', 'completed': False}, {'userId': 6, 'id': 115, 'title': 'sed et ea eum', 'completed': False}, {'userId': 6, 'id': 116, 'title': 'ipsa dolores vel facilis ut', 'completed': True}, {'userId': 6, 'id': 117, 'title': 'sequi quae est et qui qui eveniet asperiores', 'completed': False}, {'userId': 6, 'id': 118, 'title': 'quia modi consequatur vero fugiat', 'completed': False}, {'userId': 6, 'id': 119, 'title': 'corporis ducimus ea perspiciatis iste', 'completed': False}, {'userId': 6, 'id': 120, 'title': 'dolorem laboriosam vel voluptas et aliquam quasi', 'completed': False}, {'userId': 7, 'id': 121, 'title': 'inventore aut nihil minima laudantium hic qui omnis', 'completed': True}, {'userId': 7, 'id': 122, 'title': 'provident aut nobis culpa', 'completed': True}, {'userId': 7, 'id': 123, 'title': 'esse et quis iste est earum aut impedit', 'completed': False}, {'userId': 7, 'id': 124, 'title': 'qui consectetur id', 'completed': False}, {'userId': 7, 'id': 125, 'title': 'aut quasi autem iste tempore illum possimus', 'completed': False}, {'userId': 7, 'id': 126, 'title': 'ut asperiores perspiciatis veniam ipsum rerum saepe', 'completed': True}, {'userId': 7, 'id': 127, 'title': 'voluptatem libero consectetur rerum ut', 'completed': True}, {'userId': 7, 'id': 128, 'title': 'eius omnis est qui voluptatem autem', 'completed': False}, {'userId': 7, 'id': 129, 'title': 'rerum culpa quis harum', 'completed': False}, {'userId': 7, 'id': 130, 'title': 'nulla aliquid eveniet harum laborum libero alias ut unde', 'completed': True}, {'userId': 7, 'id': 131, 'title': 'qui ea incidunt quis', 'completed': False}, {'userId': 7, 'id': 132, 'title': 'qui molestiae voluptatibus velit iure harum quisquam', 'completed': True}, {'userId': 7, 'id': 133, 'title': 'et labore eos enim rerum consequatur sunt', 'completed': True}, {'userId': 7, 'id': 134, 'title': 'molestiae doloribus et laborum quod ea', 'completed': False}, {'userId': 7, 'id': 135, 'title': 'facere ipsa nam eum voluptates reiciendis vero qui', 'completed': False}, {'userId': 7, 'id': 136, 'title': 'asperiores illo tempora fuga sed ut quasi adipisci', 'completed': False}, {'userId': 7, 'id': 137, 'title': 'qui sit non', 'completed': False}, {'userId': 7, 'id': 138, 'title': 'placeat minima consequatur rem qui ut', 'completed': True}, {'userId': 7, 'id': 139, 'title': 'consequatur doloribus id possimus voluptas a voluptatem', 'completed': False}, {'userId': 7, 'id': 140, 'title': 'aut consectetur in blanditiis deserunt quia sed laboriosam', 'completed': True}, {'userId': 8, 'id': 141, 'title': 'explicabo consectetur debitis voluptates quas quae culpa rerum non', 'completed': True}, {'userId': 8, 'id': 142, 'title': 'maiores accusantium architecto necessitatibus reiciendis ea aut', 'completed': True}, {'userId': 8, 'id': 143, 'title': 'eum non recusandae cupiditate animi', 'completed': False}, {'userId': 8, 'id': 144, 'title': 'ut eum exercitationem sint', 'completed': False}, {'userId': 8, 'id': 145, 'title': 'beatae qui ullam incidunt voluptatem non nisi aliquam', 'completed': False}, {'userId': 8, 'id': 146, 'title': 'molestiae suscipit ratione nihil odio libero impedit vero totam', 'completed': True}, {'userId': 8, 'id': 147, 'title': 'eum itaque quod reprehenderit et facilis dolor autem ut', 'completed': True}, {'userId': 8, 'id': 148, 'title': 'esse quas et quo quasi exercitationem', 'completed': False}, {'userId': 8, 'id': 149, 'title': 'animi voluptas quod perferendis est', 'completed': False}, {'userId': 8, 'id': 150, 'title': 'eos amet tempore laudantium fugit a', 'completed': False}, {'userId': 8, 'id': 151, 'title': 'accusamus adipisci dicta qui quo ea explicabo sed vero', 'completed': True}, {'userId': 8, 'id': 152, 'title': 'odit eligendi recusandae doloremque cumque non', 'completed': False}, {'userId': 8, 'id': 153, 'title': 'ea aperiam consequatur qui repellat eos', 'completed': False}, {'userId': 8, 'id': 154, 'title': 'rerum non ex sapiente', 'completed': True}, {'userId': 8, 'id': 155, 'title': 'voluptatem nobis consequatur et assumenda magnam', 'completed': True}, {'userId': 8, 'id': 156, 'title': 'nam quia quia nulla repellat assumenda quibusdam sit nobis', 'completed': True}, {'userId': 8, 'id': 157, 'title': 'dolorem veniam quisquam deserunt repellendus', 'completed': True}, {'userId': 8, 'id': 158, 'title': 'debitis vitae delectus et harum accusamus aut deleniti a', 'completed': True}, {'userId': 8, 'id': 159, 'title': 'debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis', 'completed': True}, {'userId': 8, 'id': 160, 'title': 'et praesentium aliquam est', 'completed': False}, {'userId': 9, 'id': 161, 'title': 'ex hic consequuntur earum omnis alias ut occaecati culpa', 'completed': True}, {'userId': 9, 'id': 162, 'title': 'omnis laboriosam molestias animi sunt dolore', 'completed': True}, {'userId': 9, 'id': 163, 'title': 'natus corrupti maxime laudantium et voluptatem laboriosam odit', 'completed': False}, {'userId': 9, 'id': 164, 'title': 'reprehenderit quos aut aut consequatur est sed', 'completed': False}, {'userId': 9, 'id': 165, 'title': 'fugiat perferendis sed aut quidem', 'completed': False}, {'userId': 9, 'id': 166, 'title': 'quos quo possimus suscipit minima ut', 'completed': False}, {'userId': 9, 'id': 167, 'title': 'et quis minus quo a asperiores molestiae', 'completed': False}, {'userId': 9, 'id': 168, 'title': 'recusandae quia qui sunt libero', 'completed': False}, {'userId': 9, 'id': 169, 'title': 'ea odio perferendis officiis', 'completed': True}, {'userId': 9, 'id': 170, 'title': 'quisquam aliquam quia doloribus aut', 'completed': False}, {'userId': 9, 'id': 171, 'title': 'fugiat aut voluptatibus corrupti deleniti velit iste odio', 'completed': True}, {'userId': 9, 'id': 172, 'title': 'et provident amet rerum consectetur et voluptatum', 'completed': False}, {'userId': 9, 'id': 173, 'title': 'harum ad aperiam quis', 'completed': False}, {'userId': 9, 'id': 174, 'title': 'similique aut quo', 'completed': False}, {'userId': 9, 'id': 175, 'title': 'laudantium eius officia perferendis provident perspiciatis asperiores', 'completed': True}, {'userId': 9, 'id': 176, 'title': 'magni soluta corrupti ut maiores rem quidem', 'completed': False}, {'userId': 9, 'id': 177, 'title': 'et placeat temporibus voluptas est tempora quos quibusdam', 'completed': False}, {'userId': 9, 'id': 178, 'title': 'nesciunt itaque commodi tempore', 'completed': True}, {'userId': 9, 'id': 179, 'title': 'omnis consequuntur cupiditate impedit itaque ipsam quo', 'completed': True}, {'userId': 9, 'id': 180, 'title': 'debitis nisi et dolorem repellat et', 'completed': True}, {'userId': 10, 'id': 181, 'title': 'ut cupiditate sequi aliquam fuga maiores', 'completed': False}, {'userId': 10, 'id': 182, 'title': 'inventore saepe cumque et aut illum enim', 'completed': True}, {'userId': 10, 'id': 183, 'title': 'omnis nulla eum aliquam distinctio', 'completed': True}, {'userId': 10, 'id': 184, 'title': 'molestias modi perferendis perspiciatis', 'completed': False}, {'userId': 10, 'id': 185, 'title': 'voluptates dignissimos sed doloribus animi quaerat aut', 'completed': False}, {'userId': 10, 'id': 186, 'title': 'explicabo odio est et', 'completed': False}, {'userId': 10, 'id': 187, 'title': 'consequuntur animi possimus', 'completed': False}, {'userId': 10, 'id': 188, 'title': 'vel non beatae est', 'completed': True}, {'userId': 10, 'id': 189, 'title': 'culpa eius et voluptatem et', 'completed': True}, {'userId': 10, 'id': 190, 'title': 'accusamus sint iusto et voluptatem exercitationem', 'completed': True}, {'userId': 10, 'id': 191, 'title': 'temporibus atque distinctio omnis eius impedit tempore molestias pariatur', 'completed': True}, {'userId': 10, 'id': 192, 'title': 'ut quas possimus exercitationem sint voluptates', 'completed': False}, {'userId': 10, 'id': 193, 'title': 'rerum debitis voluptatem qui eveniet tempora distinctio a', 'completed': True}, {'userId': 10, 'id': 194, 'title': 'sed ut vero sit molestiae', 'completed': False}, {'userId': 10, 'id': 195, 'title': 'rerum ex veniam mollitia voluptatibus pariatur', 'completed': True}, {'userId': 10, 'id': 196, 'title': 'consequuntur aut ut fugit similique', 'completed': True}, {'userId': 10, 'id': 197, 'title': 'dignissimos quo nobis earum saepe', 'completed': True}, {'userId': 10, 'id': 198, 'title': 'quis eius est sint explicabo', 'completed': True}, {'userId': 10, 'id': 199, 'title': 'numquam repellendus a magnam', 'completed': True}, {'userId': 10, 'id': 200, 'title': 'ipsam aperiam voluptates qui', 'completed': False}]

## 2. Mostra per pantalla:

- La quantitat total de cada recurs.
- El codi d'estat de cada petició.

In [33]:
print(f"Quantitat de posts: {len(posts)} \nQuantitat de usuaris: {len(users)} \nQuantitat de todos: {len(todos)}")

Quantitat de posts: 100
Quantitat de usuaris: 10
Quantitat de todos: 200

In [37]:
print(f"Codi estat posts: {response_posts.status_code} \nCodi estat usuaris: {response_users.status_code} \nCodi estat todos: {response_todos.status_code}")

Codi estat posts: 200
Codi estat usuaris: 200
Codi estat todos: 200

## 3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [40]:
response_failed = requests.get("https://jsonplaceholder.typicode.com/company")
print(f"Codi estat: {response_failed.status_code}")

Codi estat: 404

## 4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [49]:
response_add = requests.post("https://jsonplaceholder.typicode.com/posts", json = {'userId': 1, 'title': 'Nuevo post', 'body': 'Nuevo post'})
print(f"Resposta JSON: {response_add.json()} \nCodi estat: {response_add.status_code}")

Resposta JSON: {'userId': 1, 'title': 'Nuevo post', 'body': 'Nuevo post', 'id': 101}
Codi estat: 201

## 5. Fes una petició PATCH per modificar parcialment una publicació existent.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [52]:
response_patch = requests.patch("https://jsonplaceholder.typicode.com/posts/1", json = {'title': 'Nuevo título'})
print(f"Resposta JSON: {response_patch.json()} \nCodi estat: {response_patch.status_code}")

Resposta JSON: {'userId': 1, 'id': 1, 'title': 'Nuevo título', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
Codi estat: 200

## 6. Fes una petició DELETE sobre una publicació.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [55]:
response_delete = requests.delete("https://jsonplaceholder.typicode.com/posts/1")
print(f"Resposta JSON: {response_delete.json()} \nCodi estat: {response_delete.status_code}")

Resposta JSON: {}
Codi estat: 200

# Nivell 2

## 1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

In [76]:
# API de Joc de Trons
ice_and_fire = requests.get("https://www.anapioficeandfire.com/api")
ice_and_fire.json()

{'books': 'https://www.anapioficeandfire.com/api/books',
 'characters': 'https://www.anapioficeandfire.com/api/characters',
 'houses': 'https://www.anapioficeandfire.com/api/houses'}

## 2. Llegeix la documentació de l'API:

- Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
- Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
- Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

1. Hi ha 3 endpoints diferents: Books, Characters i Houses

2. Es possible filtrar els llibres per titol o la data de publicació. Els personatges es poden filtrar per nom, génere, si és viu o no la seva cultura o l'any de neixement. I les cases es poden filtrar per nom, regió o si té armes llegendàries.

3. La resposta es en format JSON

## 3. Fes una petició GET senzilla:

- Mostra el codi d'estat de la resposta.
- Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [98]:
ice_and_fire_char = requests.get("https://www.anapioficeandfire.com/api/characters/?name=Jon Snow")
print(f"Codi resposta: {ice_and_fire_char.status_code} \nResposta JSON: {json.dumps(ice_and_fire_char.json(), indent=4)}")

Codi resposta: 200
Resposta JSON: [
    {
        "url": "https://www.anapioficeandfire.com/api/characters/583",
        "name": "Jon Snow",
        "gender": "Male",
        "culture": "Northmen",
        "born": "In 283 AC",
        "died": "",
        "titles": [
            "Lord Commander of the Night's Watch"
        ],
        "aliases": [
            "Lord Snow",
            "Ned Stark's Bastard",
            "The Snow of Winterfell",
            "The Crow-Come-Over",
            "The 998th Lord Commander of the Night's Watch",
            "The Bastard of Winterfell",
            "The Black Bastard of the Wall",
            "Lord Crow"
        ],
        "father": "",
        "mother": "",
        "spouse": "",
        "allegiances": [
            "https://www.anapioficeandfire.com/api/houses/362"
        ],
        "books": [
            "https://www.anapioficeandfire.com/api/books/5"
        ],
        "povBooks": [
            "https://www.anapioficeandfire.com/api/books/1",
            "https://www.anapioficeandfire.com/api/books/2",
            "https://www.anapioficeandfire.com/api/books/3",
            "https://www.anapioficeandfire.com/api/books/8"
        ],
        "tvSeries": [
            "Season 1",
            "Season 2",
            "Season 3",
            "Season 4",
            "Season 5",
            "Season 6"
        ],
        "playedBy": [
            "Kit Harington"
        ]
    }
]

## 4. Converteix les dades a un DataFrame de pandas:

- Mostra les primeres files del DataFrame.

In [123]:
ice_and_fire_books = requests.get("https://www.anapioficeandfire.com/api/books")
books_data = ice_and_fire_books.json()
data = pd.DataFrame(books_data).drop("url", axis = 1)
data.head(5)

,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
1,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
2,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
3,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
4,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...

## 1. Utilitza l’API d’Open Data BCN per:

- Cercar un dataset del teu interès mitjançant package_search i package_show. .

In [164]:
search = requests.get("https://opendata-ajuntament.barcelona.cat/data/api/action/package_search?q=emigrants")
data_search = search.json()
data_search

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_search',
 'success': True,
 'result': {'count': 2,
  'sort': 'fecha_publicacion desc',
  'facets': {},
  'results': [{'notes_translated': {'ca': "Nombre de persones emigrants a Barcelona per any segons el Padró Municipal d'Habitants",
     'en': 'Number of emigrant people in Barcelona by year by the Municipal Register of Inhabitants',
     'es': 'Número de emigrantes en Barcelona por año según el Padrón Municipal de Habitantes'},
    'geolocation': 'No',
    'code': 'pad_emi_mdbas',
    'url_tornada': {'ca': '', 'en': '', 'es': ''},
    'dataset_fields_description': 'Les dades dels fluxos padronals estan sotmeses a rectificacions d’acord amb els registres oficials.. Si la dada és menor que 5, s’indica com ‘’..’’',
    'fuente': "Ajuntament de Barcelona. Oficina Municipal de Dades (OMD). Padró Municipal d'Habitants",
    'private': False,
    'num_tags': 30,
    'api': 'Yes',
    'frequency': 'ANUAL',
    'id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'title_translated': {'ca': 'Persones emigrants',
     'en': 'Emigrants',
     'es': 'Personas emigrantes'},
    'metadata_modified': '2025-07-23T09:29:59.708933',
    'author': 'Gerència Municipal',
    'author_email': None,
    'isopen': True,
    'long_format': 'Yes',
    'state': 'active',
    'version': '',
    'mar_od': 'No',
    'relationships_as_object': [],
    'department': 'Oficina Municipal de Dades',
    'creator_user_id': '50d6b44b-a141-4dc6-b663-5deb4ab0dd63',
    'type': 'dataset',
    'resources': [{'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': True,
      'id': '41964dc5-927b-4a09-bf5a-59ab8927ee0e',
      'size': '56166',
      'state': 'active',
      'api_access_number': '1',
      'api_access_number_absolute': '1',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '1',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2024_pad_emi_mdbas.csv',
      'created': '2025-07-23T07:14:50.743098',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/41964dc5-927b-4a09-bf5a-59ab8927ee0e/download',
      'downloads_absolute': '1',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.535171\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-07-24T02:10:38.425714\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': None,
      'position': 0,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': False,
      'id': 'c296814f-e1fe-4e1c-bd96-3cea6c0bb4d1',
      'size': '164994',
      'state': 'active',
      'api_access_number': '0',
      'api_access_number_absolute': '0',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'JSON',
      'downloads': '0',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2024_pad_emi_mdbas.json',
      'created': '2025-07-23T07:13:33.325762',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/c296814f-e1fe-4e1c-bd96-3cea6c0bb4d1/download',
      'downloads_absolute': '0',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.556494\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'JSON\', \'created\': \'2025-07-24T02:10:38.454985\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.\'}',
      'last_modified': None,
      'position': 1,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': True,
      'id': '4dced815-e9ae-445a-97f4-d4adb080d3db',
      'size': '56158',
      'state': 'active',
      'api_access_number': '1',
      'api_access_number_absolute': '1',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '0',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2023_pad_emi_mdbas.csv',
      'created': '2025-07-23T07:12:15.328632',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/4dced815-e9ae-445a-97f4-d4adb080d3db/download',
      'downloads_absolute': '0',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.582263\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-07-24T02:10:38.484592\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': None,
      'position': 2,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': False,
      'id': '15e6fdb8-dacd-49ec-81fb-a76902c0ca99',
      'size': '164986',
      'state': 'active',
      'api_access_number': '0',
      'api_access_number_absolute': '0',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'JSON',
      'downloads': '1',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2023_pad_emi_mdbas.json',
      'created': '2025-07-23T07:10:57.785945',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/15e6fdb8-dacd-49ec-81fb-a76902c0ca99/download',
      'downloads_absolute': '1',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.605763\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'JSON\', \'created\': \'2025-07-24T02:10:38.516511\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.\'}',
      'last_modified': None,
      'position': 3,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': True,
      'id': '44b948c5-adcb-4b19-8dd2-aea43769206e',
      'size': '56154',
      'state': 'active',
      'api_access_number': '1',
      'api_access_number_absolute': '1',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '1',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2022_pad_emi_mdbas.csv',
      'created': '2025-07-23T07:09:40.082049',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/44b948c5-adcb-4b19-8dd2-aea43769206e/download',
      'downloads_absolute': '1',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.633797\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-07-24T02:10:38.538914\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': None,
      'position': 4,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': False,
      'id': '78b9bac7-e20c-4611-bf56-ba8604d8648f',
      'size': '164982',
      'state': 'active',
      'api_access_number': '0',
      'api_access_number_absolute': '0',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'JSON',
      'downloads': '1',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2022_pad_emi_mdbas.json',
      'created': '2025-07-23T07:08:22.935173',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/78b9bac7-e20c-4611-bf56-ba8604d8648f/download',
      'downloads_absolute': '1',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.664102\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'JSON\', \'created\': \'2025-07-24T02:10:38.570988\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.\'}',
      'last_modified': None,
      'position': 5,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': True,
      'id': '657384c4-8d9b-45cb-845d-0649eb88e35a',
      'size': '56172',
      'state': 'active',
      'api_access_number': '1',
      'api_access_number_absolute': '1',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '0',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2021_pad_emi_mdbas.csv',
      'created': '2025-07-23T07:07:04.945912',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/657384c4-8d9b-45cb-845d-0649eb88e35a/download',
      'downloads_absolute': '0',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.682437\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-07-24T02:10:38.595194\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': None,
      'position': 6,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': False,
      'id': 'f55e3330-52ad-41fd-b57e-3ec846555e04',
      'size': '165000',
      'state': 'active',
      'api_access_number': '0',
      'api_access_number_absolute': '0',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'JSON',
      'downloads': '1',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2021_pad_emi_mdbas.json',
      'created': '2025-07-23T07:05:47.722924',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/f55e3330-52ad-41fd-b57e-3ec846555e04/download',
      'downloads_absolute': '1',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.705310\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'JSON\', \'created\': \'2025-07-24T02:10:38.618773\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.\'}',
      'last_modified': None,
      'position': 7,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': True,
      'id': '084db113-32b9-451f-9310-22356d4882c6',
      'size': '56153',
      'state': 'active',
      'api_access_number': '1',
      'api_access_number_absolute': '1',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '0',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2020_pad_emi_mdbas.csv',
      'created': '2025-07-23T07:04:30.177632',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/084db113-32b9-451f-9310-22356d4882c6/download',
      'downloads_absolute': '0',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.734625\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-07-24T02:10:38.645156\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': None,
      'position': 8,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': False,
      'id': 'cc8d94cd-bb2f-4325-9663-1b939f3944ec',
      'size': '164981',
      'state': 'active',
      'api_access_number': '0',
      'api_access_number_absolute': '0',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'JSON',
      'downloads': '0',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2020_pad_emi_mdbas.json',
      'created': '2025-07-23T07:03:12.474514',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/cc8d94cd-bb2f-4325-9663-1b939f3944ec/download',
      'downloads_absolute': '0',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.754301\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'JSON\', \'created\': \'2025-07-24T02:10:38.677616\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.\'}',
      'last_modified': None,
      'position': 9,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': True,
      'id': '54a9847b-c053-4bde-a5d1-2d1942c72587',
      'size': '56147',
      'state': 'active',
      'api_access_number': '1',
      'api_access_number_absolute': '1',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '0',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2019_pad_emi_mdbas.csv',
      'created': '2025-07-23T07:01:55.201656',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/54a9847b-c053-4bde-a5d1-2d1942c72587/download',
      'downloads_absolute': '0',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.775473\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-07-24T02:10:38.706393\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': None,
      'position': 10,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': False,
      'id': 'd6de9d05-a9db-41a1-91ce-430394594aae',
      'size': '164975',
      'state': 'active',
      'api_access_number': '0',
      'api_access_number_absolute': '0',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'JSON',
      'downloads': '0',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2019_pad_emi_mdbas.json',
      'created': '2025-07-23T07:00:37.988638',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/d6de9d05-a9db-41a1-91ce-430394594aae/download',
      'downloads_absolute': '0',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-07-29T02:12:01.810196\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'JSON\', \'created\': \'2025-07-24T02:10:38.727801\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.\'}',
      'last_modified': None,
      'position': 11,
      'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
      'resource_type': None},
     {'cache_last_updated': None,
      'token_type': '',
      'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
      'datastore_active': True,
      'id': 'a9b7b661-c309-4a35-9b84-a02292324de7',
      'size': '56153',
      'state': 'active',
      'api_access_number': '1',
      'api_access_number_absolute': '1',
      'token_required': 'No',
      'hash': '',
      'description': '',
      'format': 'CSV',
      'downloads': '0',
      'mimetype_inner': None,
      'url_type': None,
      'token_provider': '',
      'hide_url': 'No',
      'mimetype': None,
      'cache_url': None,
      'name': '2018_pad_emi_mdbas.csv',
      'created': '2025-07-23T06:59:20.975156',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/a9b7b661-c309-4a35-9b84-a02292324de7/download',
      'downloads_absolute': '0',
      'map_visualization_res': 'none',

In [166]:
show = requests.get("https://opendata-ajuntament.barcelona.cat/data/api/action/package_show?name_or_id=3d317361-0be9-4178-8566-4ff0b33d65a3")
data_show = show.json()
data_show

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_show',
 'success': True,
 'result': {'notes_translated': {'ca': "Nombre de persones emigrants a Barcelona per any segons el Padró Municipal d'Habitants",
   'en': 'Number of emigrant people in Barcelona by year by the Municipal Register of Inhabitants',
   'es': 'Número de emigrantes en Barcelona por año según el Padrón Municipal de Habitantes'},
  'geolocation': 'No',
  'code': 'pad_emi_mdbas',
  'url_tornada': {'ca': '', 'en': '', 'es': ''},
  'dataset_fields_description': 'Les dades dels fluxos padronals estan sotmeses a rectificacions d’acord amb els registres oficials.. Si la dada és menor que 5, s’indica com ‘’..’’',
  'fuente': "Ajuntament de Barcelona. Oficina Municipal de Dades (OMD). Padró Municipal d'Habitants",
  'private': False,
  'num_tags': 30,
  'api': 'Yes',
  'frequency': 'ANUAL',
  'id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
  'title_translated': {'ca': 'Persones emigrants',
   'en': 'Emigrants',
   'es': 'Personas emigrantes'},
  'metadata_modified': '2025-07-23T09:29:59.708933',
  'author': 'Gerència Municipal',
  'author_email': None,
  'isopen': True,
  'long_format': 'Yes',
  'state': 'active',
  'version': '',
  'mar_od': 'No',
  'relationships_as_object': [],
  'department': 'Oficina Municipal de Dades',
  'creator_user_id': '50d6b44b-a141-4dc6-b663-5deb4ab0dd63',
  'type': 'dataset',
  'resources': [{'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': True,
    'id': '41964dc5-927b-4a09-bf5a-59ab8927ee0e',
    'size': '56166',
    'state': 'active',
    'api_access_number': 1,
    'api_access_number_absolute': 1,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 1,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2024_pad_emi_mdbas.csv',
    'created': '2025-07-23T07:14:50.743098',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/41964dc5-927b-4a09-bf5a-59ab8927ee0e/download',
    'downloads_absolute': 1,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.535171',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-07-24T02:10:38.425714',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 0,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': False,
    'id': 'c296814f-e1fe-4e1c-bd96-3cea6c0bb4d1',
    'size': '164994',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 0,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2024_pad_emi_mdbas.json',
    'created': '2025-07-23T07:13:33.325762',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/c296814f-e1fe-4e1c-bd96-3cea6c0bb4d1/download',
    'downloads_absolute': 0,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.556494',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-07-24T02:10:38.454985',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 1,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': True,
    'id': '4dced815-e9ae-445a-97f4-d4adb080d3db',
    'size': '56158',
    'state': 'active',
    'api_access_number': 1,
    'api_access_number_absolute': 1,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 0,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2023_pad_emi_mdbas.csv',
    'created': '2025-07-23T07:12:15.328632',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/4dced815-e9ae-445a-97f4-d4adb080d3db/download',
    'downloads_absolute': 0,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.582263',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-07-24T02:10:38.484592',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 2,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': False,
    'id': '15e6fdb8-dacd-49ec-81fb-a76902c0ca99',
    'size': '164986',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 1,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2023_pad_emi_mdbas.json',
    'created': '2025-07-23T07:10:57.785945',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/15e6fdb8-dacd-49ec-81fb-a76902c0ca99/download',
    'downloads_absolute': 1,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.605763',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-07-24T02:10:38.516511',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 3,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': True,
    'id': '44b948c5-adcb-4b19-8dd2-aea43769206e',
    'size': '56154',
    'state': 'active',
    'api_access_number': 1,
    'api_access_number_absolute': 1,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 1,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2022_pad_emi_mdbas.csv',
    'created': '2025-07-23T07:09:40.082049',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/44b948c5-adcb-4b19-8dd2-aea43769206e/download',
    'downloads_absolute': 1,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.633797',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-07-24T02:10:38.538914',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 4,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': False,
    'id': '78b9bac7-e20c-4611-bf56-ba8604d8648f',
    'size': '164982',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 1,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2022_pad_emi_mdbas.json',
    'created': '2025-07-23T07:08:22.935173',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/78b9bac7-e20c-4611-bf56-ba8604d8648f/download',
    'downloads_absolute': 1,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.664102',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-07-24T02:10:38.570988',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 5,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': True,
    'id': '657384c4-8d9b-45cb-845d-0649eb88e35a',
    'size': '56172',
    'state': 'active',
    'api_access_number': 1,
    'api_access_number_absolute': 1,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 0,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2021_pad_emi_mdbas.csv',
    'created': '2025-07-23T07:07:04.945912',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/657384c4-8d9b-45cb-845d-0649eb88e35a/download',
    'downloads_absolute': 0,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.682437',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-07-24T02:10:38.595194',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 6,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': False,
    'id': 'f55e3330-52ad-41fd-b57e-3ec846555e04',
    'size': '165000',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 1,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2021_pad_emi_mdbas.json',
    'created': '2025-07-23T07:05:47.722924',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/f55e3330-52ad-41fd-b57e-3ec846555e04/download',
    'downloads_absolute': 1,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.705310',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-07-24T02:10:38.618773',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 7,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': True,
    'id': '084db113-32b9-451f-9310-22356d4882c6',
    'size': '56153',
    'state': 'active',
    'api_access_number': 1,
    'api_access_number_absolute': 1,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 0,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2020_pad_emi_mdbas.csv',
    'created': '2025-07-23T07:04:30.177632',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/084db113-32b9-451f-9310-22356d4882c6/download',
    'downloads_absolute': 0,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.734625',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-07-24T02:10:38.645156',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 8,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': False,
    'id': 'cc8d94cd-bb2f-4325-9663-1b939f3944ec',
    'size': '164981',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 0,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2020_pad_emi_mdbas.json',
    'created': '2025-07-23T07:03:12.474514',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/cc8d94cd-bb2f-4325-9663-1b939f3944ec/download',
    'downloads_absolute': 0,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.754301',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-07-24T02:10:38.677616',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 9,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': True,
    'id': '54a9847b-c053-4bde-a5d1-2d1942c72587',
    'size': '56147',
    'state': 'active',
    'api_access_number': 1,
    'api_access_number_absolute': 1,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 0,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2019_pad_emi_mdbas.csv',
    'created': '2025-07-23T07:01:55.201656',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/54a9847b-c053-4bde-a5d1-2d1942c72587/download',
    'downloads_absolute': 0,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.775473',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-07-24T02:10:38.706393',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 10,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': False,
    'id': 'd6de9d05-a9db-41a1-91ce-430394594aae',
    'size': '164975',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 0,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2019_pad_emi_mdbas.json',
    'created': '2025-07-23T07:00:37.988638',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/d6de9d05-a9db-41a1-91ce-430394594aae/download',
    'downloads_absolute': 0,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.810196',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-07-24T02:10:38.727801',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 11,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': True,
    'id': 'a9b7b661-c309-4a35-9b84-a02292324de7',
    'size': '56153',
    'state': 'active',
    'api_access_number': 1,
    'api_access_number_absolute': 1,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 0,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2018_pad_emi_mdbas.csv',
    'created': '2025-07-23T06:59:20.975156',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/a9b7b661-c309-4a35-9b84-a02292324de7/download',
    'downloads_absolute': 0,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-07-29T02:12:01.836199',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-07-24T02:10:38.758900',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 12,
    'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
    'datastore_active': False,
    'id': 'c7a140ea-da68-4581-8696-ccb377b7856f',
    'size': '164981',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 0,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2018_pad_emi_mdbas.json',
    'created': '2025-07-23T06:58:04.761335',

## 2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON

- Seleccionem "Nombre de persones emigrants a Barcelona per any segons el Padró Municipal d'Habitants" que té datasets en CSV i JSON

## 3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

- Recuperar almenys 100 registres.

In [265]:
data_get = requests.get("https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=41964dc5-927b-4a09-bf5a-59ab8927ee0e&limit=120&q=Eixample")
data_get_json = data_get.json()
print(f"Quantitat de resultats: {len(data_get_json["result"]["records"])}")

Quantitat de resultats: 120

## 4. Converteix els resultats a un DataFrame.

In [270]:
data_pd = pd.DataFrame(data_get_json["result"]["records"])
data_pd.head()

,Codi_Districte,Nom_Districte,rank,Nom_Barri,AEB,_full_count,Seccio_Censal,Valor,Codi_Barri,_id,Any
0,2,Eixample,0.057309,la Sagrada Família,26,173,2043,56,6,97,2024
1,2,Eixample,0.057309,el Fort Pienc,20,173,2002,508,5,56,2024
2,2,Eixample,0.057309,el Fort Pienc,20,173,2003,34,5,57,2024
3,2,Eixample,0.057309,el Fort Pienc,20,173,2004,62,5,58,2024
4,2,Eixample,0.057309,el Fort Pienc,20,173,2005,96,5,59,2024

## 5. Desa el DataFrame en un fitxer .csv

In [273]:
data_pd.to_csv("emigrants_eixample.csv")